name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/zeya-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t flask-app .

      - name: Tag image with latest and SHA
        run: |
          docker tag flask-app:latest 255945442255.dkr.ecr.us-east-1.amazonaws.com/zeya-flask-private-repository:latest
          docker tag flask-app:latest 255945442255.dkr.ecr.us-east-1.amazonaws.com/zeya-flask-private-repository:${{ github.sha }}

      - name: Push both tags
        run: |
          docker push 255945442255.dkr.ecr.us-east-1.amazonaws.com/zeya-flask-private-repository:latest
          docker push 255945442255.dkr.ecr.us-east-1.amazonaws.com/zeya-flask-private-repository:${{ github.sha }}
